return {
  "local M = {}",
  "",
  "---@param fn fun(): boolean",
  "function M.retry(fn, attempts)",
  "  attempts = attempts or 3",
  "  for i = 1, attempts do",
  "    local ok, err = pcall(fn)",
  "    if ok then return true, nil end",
  '    vim.notify(("attempt %d failed"):format(i), vim.log.levels.WARN)',
  "    vim.uv.sleep(0.1 * 2 ^ i)",
  "  end",
  '  return false, "exhausted"',
  "end",
  "",
  'local CONFIG = { retries = 3, timeout_ms = 1500, tags = { "a", "b" } }',
  "M.default = CONFIG.retries + CONFIG.timeout_ms / 1000",
  "",
  "return M",
}
